### ISSUE TITLE
Crash with MC 1.20.6, Fabric Loader 0.15.11

### ISSUE THREAD

**Issue by yutotakano** [gliscowo/idwtialsimmoedm#20]
Hi! I love this mod, it really reduces the time it takes to look up an enchantment in the wiki.

I've just upgraded my client to MC 1.20.6, Fabric Loader 0.15.11 and I'm hitting a crash upon trying to load a singleplayer world that I suspect is related to this mod. I've attached the relevant bit of the log below, would you look into it and be able to fix it?

<details>
<summary>Logs</summary>

```
[23:54:36] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[23:54:40] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:40] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:40] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:40] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:40] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:40] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:40] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:40] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:40] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:40] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:41] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:41] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:42] [Render thread/INFO]: Preparing spawn area: 0%
[23:54:42] [Render thread/INFO]: Time elapsed: 6600 ms
[23:54:43] [Server thread/INFO]: Changing simulation distance to 11, from 0
[23:54:45] [Server thread/INFO]: myuser[local:E:b22cfa9f] logged in with entity id 3 at (-11065.478294045988, 65.0, -10209.785827564781)
[23:54:45] [Server thread/INFO]: myuser joined the game
[23:54:45] [Render thread/INFO]: Reloading pipeline on dimension change: NamespacedId{namespace='minecraft', name='overworld'} => NamespacedId{namespace='minecraft', name='overworld'}
[23:54:45] [Render thread/INFO]: Destroying pipeline NamespacedId{namespace='minecraft', name='overworld'}
[23:54:45] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[23:54:46] [Render thread/INFO]: Started 2 worker threads
[23:54:47] [Render thread/ERROR]: Unreported exception thrown!
java.lang.AbstractMethodError: Receiver class io.wispforest.idwtialsimmoedm.IdwtialsimmoedmClient$$Lambda/0x0000018741bc0f28 does not define or inherit an implementation of the resolved method 'abstract void getTooltip(net.minecraft.class_1799, net.minecraft.class_1792$class_9635, net.minecraft.class_1836, java.util.List)' of interface net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:35) ~[fabric-item-api-v1-8.2.1+8e8943b6b0-66d14f010e695c21.jar:?]
	at net.minecraft.class_1799.handler$zfh000$fabric-item-api-v1$getTooltip(class_1799.java:1609) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7950(class_1799.java:796) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_53863(class_310.java:934) ~[client-intermediary.jar:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_7454.method_43796(class_7454.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_1126.method_4799(class_1126.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_1124$class_7457.method_43807(class_1124.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_1124.method_43804(class_1124.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_43759(class_310.java:2810) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11106(class_634.java:1475) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11054(class_2788.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[23:54:50] [Server thread/INFO]: Stopping server
[23:54:50] [Server thread/INFO]: Saving players
[23:54:51] [Server thread/INFO]: Saving worlds
```
</details>

**Comment by Noaaan** [comment]
This is definitely due to 1.20.5+, since they changed tooltip handling. As such, this version of idwtialsimmoedm isn't compatible with latest

**Comment by yutotakano** [comment]
Thanks for the prompt reply! 1.20.5 seems to have broken quite a lot of mods and datapacks, so I understand it's quite big of a breaking change — please take however much time you want! I think I'll survive without the mod for a while.

**Comment by gliscowo** [comment]
I've now ported the mod to 1.20.6, available [here](https://modrinth.com/mod/idwtialsimmoedm/version/0.3.0+1.20.3)
Cheers

**Comment by yutotakano** [comment]
Thanks!
